version: "3.9"

services:
  backend:
    build:
      context: ./back
    environment:
      - PORT=8020
    env_file:
      - ./back/.env
    ports:
      - "8001:8020"
    volumes:
       - ./back:/app
    command: >
      sh -c 'chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh'
    depends_on:
      - database


  database:
    image: postgres:13-alpine
    restart: always
    command: -p 5432
    env_file:
      - ./back/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data: