name: Python CI

on:
  push:
    branches:
        - '**'

  pull_request:
    branches:
        - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r ./back/requirements.dev.txt

    - name: Black formatting
      run: |
        black --check .

    - name: Test run
      run: |
        pytest ./back
      
    - name: Test coverage
      run: |
        pytest ./back --cov=./back/core --cov-report=term --cov-fail-under=60
      

    - name: Pylint linting
      run: |
        pylint --rcfile=./back/.pylintrc ./back/core
        pylint --rcfile=./back/.pylintrc ./back/api